# Spring 基本配置
spring:
  # 引入子配置文件。
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/school-book-reading-system?useUnicode=true&useSSL=false&characterEncoding=utf8
    username: root
    password: root

# Mybatis 配置
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml